server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission?characterEncoding=utf-8&useSSL=true
    username: root
    password: xxxx
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

amsso:
  baseurl: http://localhost:8080













